### PR TITLE
2 fix background color mp

### LINKED ISSUE #2: # 2 Change background color
Its hurting my eyes

### PR DESCRIPTION
**Pull request by marcusp619**
Change background color to peru

Fixes #2

### CODE REVIEW

**Comment by djcaraballo** [comment]
Not really feeling the peru. Can we come up with another color?

**Comment by marcusp619** [comment]
What did you have in mind 🙄

**Comment by djcaraballo** [comment]
What about cornflower blue?

**Comment by djcaraballo** [comment]
I love the new color! Merging now!

**Pull request merged**
